version: "3"

services:

  # sql-server:
  #   image: devlucasmello/tc-sql-server:latest
  #   container_name: tc-sql-server
  #   build: 
  #     context: ../sql
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     SA_PASSWORD: "Lm@518792"
  #     ACCEPT_EULA: "Y"

  crud:
    image: devlucasmello/tc-gateway-crud:latest
    container_name: tc-gateway-crud
    build:
      context: ../src
      dockerfile: ./api gateways/TC.Bff.Crud/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    depends_on:      
      - api-usuario

  api-identidade:
    image: devlucasmello/tc-api-identidade:latest
    container_name: tc-api-identidade
    build:
      context: ../src
      dockerfile: ./services/TC.Identidade.API/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5101
    # depends_on:
    #   - sql-server

  api-usuario:
    image: devlucasmello/tc-api-usuario:latest
    container_name: tc-api-usuario
    build:
      context: ../src
      dockerfile: ./services/TC.Usuarios.API/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5301
    depends_on:      
      - api-identidade